name: All_ON_PUSH

on: push

jobs:
  All_ON_PUSH:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        shell: bash
      - run: echo '${{ github.ref }} ...  ${{ github.sha }}'
      - name: build-site
        run: npm run build
      - name: upload surge service and generate preview URL
        id: deploy
        run: |
          export GITHUB_SHA=${{ github.sha }}
          export GITHUB_SHA_SUB=${GITHUB_SHA: 0: 7 }
          export DEPLOY_DOMAIN=https://preview-$GITHUB_SHA_SUB-tdesign-vue-next-starter.surge.sh
          npx surge --project ./dist --domain $DEPLOY_DOMAIN --token ${{ secrets.TDESIGN_SURGE_TOKEN }}
          echo the preview URL is $DEPLOY_DOMAIN
        if: ${{ success() }}
      - run: echo "ðŸš€ This job's status is ${{ job.status }}."
